{% set name = "jupyterlab-geojson" %}
{% set version = "3.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab-geojson-{{ version }}.tar.gz
  sha256: 45da6d1df8fedf8edf3fc6bdf58106d99d7b4a982df978342512b37c75393825

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - jupyter-packaging >=0.7.9,<0.8.0
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - pip check
    - test -f "${PREFIX}/share/jupyter/labextensions/@jupyterlab/geojson-extension/package.json"                                    # [unix]
    - if exist %PREFIX%\\share\\jupyter\\labextensions\\@jupyterlab\\geojson-extension\\package.json (exit 0) else (exit 1)         # [win]
  requires:
    - pip

about:
  home: https://github.com/jupyterlab/jupyter-renderers
  summary: GeoJSON renderer for JupyterLab
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fcollonval
    - jtpio
    - jasongrout
    - blink1073
