{% set name = "jupyterlab-geojson" %}
{% set version = "3.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: cc7f6015f75f7816240402880134cd7174af64fbef010b1556071729f98a291f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatch-jupyter-builder >=0.5
    - hatch-nodejs-version
    - hatchling >=1.5.0
    - jupyterlab >=4,<5
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - pip check
    - test -f "${PREFIX}/share/jupyter/labextensions/@jupyterlab/geojson-extension/package.json"                                    # [unix]
    - if exist %PREFIX%\\share\\jupyter\\labextensions\\@jupyterlab\\geojson-extension\\package.json (exit 0) else (exit 1)         # [win]
  requires:
    - pip

about:
  home: https://github.com/jupyterlab/jupyter-renderers
  summary: GeoJSON renderer for JupyterLab
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - jupyterlab_geojson/labextension/static/third-party-licenses.json

extra:
  recipe-maintainers:
    - jtpio
    - jasongrout
    - blink1073
